jobs:

- job: Windows

  pool:
    vmImage: 'windows-2019'

  variables:
    NUGET_PACKAGES: $(Agent.WorkFolder)\.nuget
    NUGET_HTTP_CACHE_PATH: $(Agent.WorkFolder)\.nuget-http-cache

  steps:
  - task: UseGitVersion@5
    displayName: gitversion
    inputs:
      versionSpec: '5.x'
      useConfigFile: true
      configFilePath: 'gitversion.yml'

  - task: MSBuild@1
    inputs:
      solution: src/SQLitePCLRaw.Wasm.sln
      msbuildArguments: /r /p:Configuration=Release "/p:PackageOutputPath=$(build.artifactstagingdirectory)\nuget" "/p:PackageVersion=%GITVERSION_FullSemVer%" "/p:InformationalVersion=%GITVERSION_InformationalVersion%" /detailedsummary
  
  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: uno.sqlitepclwasmprovider-drop
      publishLocation: Container

- job: Linux
  container: unoplatform/wasm-build:2.0

  pool:
    vmImage: 'ubuntu-latest'

  variables:
    DotnetRuntimePath: /usr/share/dotnet

  steps:
  - checkout: self
    clean: true

  - task: UseDotNet@2
    displayName: 'Use .Net Core runtime 2.1.0'
    inputs:
      packageType: runtime
      version: 2.1.0
      installationPath: '$(DotnetRuntimePath)'

  - task: GitVersion@5
    inputs:
      useConfigFile: true
      configFilePath: gitversion.yml
      
  - bash: |
      cd ~
      git clone --branch 1.39.11 https://github.com/emscripten-core/emsdk
      cd emsdk
      ./emsdk install sdk-1.39.11
      ./emsdk activate sdk-1.39.11

    displayName: 'Setup Emscripten'

  - bash: |
      source ~/emsdk/emsdk_env.sh
      msbuild /r /p:Configuration=Release "/p:PackageOutputPath=$(build.artifactstagingdirectory)\nuget" "/p:PackageVersion=$GITVERSION_FULLSEMVER" "/p:InformationalVersion=$GITVERSION_INFORMATIONALVERSION" ./src/samples/EFCoreSample/EFCoreSample.Wasm/EFCoreSample.Wasm.csproj

    displayName: 'Build Wasm Head'

  - task: PublishBuildArtifacts@1
    displayName: Publish Package Artifacts
    inputs:
      pathToPublish: ./src/samples/EFCoreSample/EFCoreSample.Wasm/bin/Release/netstandard2.0/dist
      artifactType: container
      artifactName: EFCoreSample-Wasm