jobs:

- job: Windows

  pool:
    vmImage: 'windows-2019'

  variables:
    NUGET_PACKAGES: $(Agent.WorkFolder)\.nuget
    NUGET_HTTP_CACHE_PATH: $(Agent.WorkFolder)\.nuget-http-cache

  steps:
  - task: UseGitVersion@5
    displayName: gitversion
    inputs:
      versionSpec: '5.x'
      useConfigFile: true
      configFilePath: 'gitversion.yml'

  - task: UseDotNet@2
    displayName: 'Use .NET 5 SDK'
    inputs:
      version: 5.x

  - task: UseDotNet@2
    displayName: 'Use .NET 6 SDK'
    inputs:
      version: 6.x
      includePreviewVersions: true

  - powershell: |
      dotnet build /r /p:Configuration=Release src/SQLitePCLRaw.Wasm.sln "/p:PackageOutputPath=$(build.artifactstagingdirectory)\nuget" "/p:PackageVersion=%GITVERSION_FullSemVer%" "/p:InformationalVersion=%GITVERSION_InformationalVersion%" /detailedsummary
  
  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: uno.sqlitepclwasmprovider-drop
      publishLocation: Container

- job: Linux
  container: unoplatform/wasm-build:3.0

  pool:
    vmImage: 'ubuntu-latest'

  variables:
    DotnetRuntimePath: /usr/share/dotnet

  steps:
  - checkout: self
    clean: true

  - task: UseDotNet@2
    displayName: 'Use .NET 5 SDK'
    inputs:
      version: 5.x

  - task: UseDotNet@2
    displayName: 'Use .NET 6 SDK'
    inputs:
      version: 6.x
      includePreviewVersions: true

  - task: GitVersion@5
    inputs:
      useConfigFile: true
      configFilePath: gitversion.yml

  - bash: |
      dotnet msbuild /r /p:Configuration=Release "/p:PackageOutputPath=$(build.artifactstagingdirectory)\nuget" "/p:PackageVersion=$GITVERSION_FULLSEMVER" "/p:InformationalVersion=$GITVERSION_INFORMATIONALVERSION" ./src/samples/EFCoreSample/EFCoreSample.Wasm/EFCoreSample.Wasm.csproj

    displayName: 'Build Wasm Head'

  - task: PublishBuildArtifacts@1
    displayName: Publish Package Artifacts
    inputs:
      pathToPublish: ./src/samples/EFCoreSample/EFCoreSample.Wasm/bin/Release/net5.0/dist
      artifactType: container
      artifactName: EFCoreSample-Wasm